eureka:
  instance:
    hostname: ${spring.application.name}.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${application.eureka.url}/eureka
    enabled: true
spring:
  application:
    name: api-gateway
application:
  eureka:
    url: https://reloadly-eureka-service.herokuapp.com


