eureka:
  client:
    serviceUrl:
      defaultZone: ${application.eureka.url}/eureka
    instance:
    preferIpAddress: true
    enabled: true
spring:
  application:
    name: api-gateway
application:
  eureka:
    url: https://reloadly-eureka-service.herokuapp.com


