eureka:
  instance:
    hostname: ${EUREKA_URL}.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}/eureka/

server:
  port: 9093
spring:
  application:
    name: api-gateway

