eureka:
  client:
    service-url: ${application.eureka.url}
spring:
  application:
    name: api-gateway

application:
  eureka:
    url: https://reloadly-eureka-service.herokuapp.com
server:
  port: 9093

