eureka:
  instance:
    hostname: ${application.name}.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.url}/eureka/
  url: reloadly-eureka-service.herokuapp.com

spring:
  application:
    name: api-gateway


