eureka:
  client:
    eureka-server-port: 8761
    enabled: true
    fetch-registry: true
    proxy-host: ${application.eureka.url}
spring:
  application:
    name: api-gateway

application:
  eureka:
    url: https://reloadly-eureka-service.herokuapp.com


