eureka:
  client:
    serviceUrl:
      defaultZone: ${application.eureka.url}/eureka
    enabled: true
    eureka-server-port: 8761
spring:
  application:
    name: api-gateway

application:
  eureka:
    url: https://reloadly-eureka-service.herokuapp.com


