eureka:
  instance:
    hostname: ${APP_NAME}.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://reloadly-eureka-service.herokuapp.com/

server:
  port: 9093
spring:
  application:
    name: api-gateway

