eureka:
  client:
    service-url: ${application.eureka.url}/eureka
spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
application:
  eureka:
    url: https://reloadly-eureka-service.herokuapp.com
server:
  port: 9093

