eureka:
  instance:
    hostname: ${application.name}.herokuapp.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${application.url}/eureka
application:
  url: https://reloadly-gate.herokuapp.com

spring:
  application:
    name: api-gateway


