eureka:
  client:
    eureka-server-port: 8761
    enabled: true
    fetch-registry: true
    webclient:
      enabled: true
    service-url: https://reloadly-eureka-service.herokuapp.com
spring:
  application:
    name: api-gateway

application:
  eureka:
    url: https://reloadly-eureka-service.herokuapp.com


