spring:
  application:
    name: reloadly-gate
  cloud:
    discovery:
      enabled: true 
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: https://reloadly-eureka-service.herokuapp.com/eureka/
